theme = "dracula"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
rulers = [100]
true-color = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "version-control"]

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
Z = { Z = ":wq" }

[keys.normal.g]
o = [ "goto_definition", "vsplit" ]
