theme = "dracula"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
Z = { Z = ":wq" }

[keys.normal.g]
o = [ "goto_definition", "vsplit" ]
