[[language]]
name = "python"
language-servers = [ "pyright" ]
auto-format = true

  [language.formatter]
  command = "sh"
  args = [ "-c", "ruff check --select I --fix --quiet - | ruff format - --quiet" ]

[[language]]
name = "svelte"
auto-format = true
roots = ["svelte.config.js", "svelte.config.ts"]

  [language.formatter]
  command = "prettier"
  args = ["--parser", "svelte"]


[[language]]
name = "typescript"
auto-format = true

  [language.formatter]
  command = "prettier"
  args = ["--parser", "typescript"]

[[language]]
name = "go"
auto-format = true

  [language.formatter]
  command = "gofmt"
